version: '2'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    ports:
      - 8181:8181
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=b-2.sinkcluster.d6avt2.c3.kafka.ap-south-1.amazonaws.com:9092,b-1.sinkcluster.d6avt2.c3.kafka.ap-south-1.amazonaws.com:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081