server:
  port: 8082
timer:
  interval: 500
  initialDelay: 1000
spring:
  kafka:
    acknowledgment: all
    maxBlockTime: 120000
    bufferMemory: 70554432
    sendBufferBytes: 5242880
    bootstrapAddress: b-3.testcluster.7gmdra.c4.kafka.ap-south-1.amazonaws.com:9092,b-1.testcluster.7gmdra.c4.kafka.ap-south-1.amazonaws.com:9092,b-2.testcluster.7gmdra.c4.kafka.ap-south-1.amazonaws.com:9092
    maxPollInterval: 600000
    maxInFlightReqPerConnInParallel: 5
    maxInFlightReqPerConnInSync: 1
    deliveryTimeoutMs: 60000
    producerRetryTimeOutMilliSeconds: 60000
    heartBeatsIntervalInMilli: 3000
    sessionTimeOutInMilli: 10000
    autoCommitInterval: 5000
    releaseTopic: releasex-4
    rf: 2
    partitions: 3
    minIsr: 2
    fallbackTopic : fallback
