spring:
  kafka:
    acknowledgment: all
    maxBlockTime: 120000
    bufferMemory: 70554432
    sendBufferBytes: 5242880
    bootstrapAddress: localhost:9092
    maxPollInterval: 600000
    maxInFlightReqPerConnInParallel: 5
    maxInFlightReqPerConnInSync: 1
    deliveryTimeoutMs: 60000
    producerRetryTimeOutMilliSeconds: 60000
    heartBeatsIntervalInMilli: 3000
    sessionTimeOutInMilli: 10000
    autoCommitInterval: 5000
    groupId: treasuryGroupId
    kafkaListenerDefaultContainerFactory: kafkaListenerContainerFactory
    releaseTopic: release
    rf: 1
    partitions: 1
    minIsr: 1
    fallbackTopic : fallback
    onHoldSettlement:
      releaseTopic: onHoldSettlementRelease
    dmsIdDataAggregationForInvoicing:
      dmsListTopic: dmsListForInvoice
      autoStartupFlagForDmsIdConsumer: true
      batchSizeForDmsIdPoll: 5
      consumerContainerFactoryForDmsIdListener: dmsIdKafkaListenerFactoryBatch
      dmsAggregatedDataTopic: dailyAggregatedDataForInvoice
      batchSizeForDmsAggregatedDataPoll: 1000
      autoStartupFlagForDmsAggregatedDataConsumer: true