server:
  port: 8082
timer:
  interval: 500
  initialDelay: 1000
spring:
  main:
    web-application-type: none
  kafka:
    propertiesFilePath: src/main/resources/kafka_sasl.properties
    messageFormat: JSON #JSON,JSON_WITH_SCHEMA,AVRO, PROTOBUF
    json:
      mainTopic: test-topic
      fallbackTopic : fallback
      schemaFile: src/main/resources/TradeJsonSchema.json
      schemaName: testjson
    avro:
      mainTopic: test-avro
      fallbackTopic: fallback
      schemaFile: src/main/resources/Trade.avsc
      schemaName: testavro
    protobuf:
      mainTopic: test-avro
      fallbackTopic: fallback
      schemaName: testprotobuf


