AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DestinationKafkaClusterBootstrap:
    Type: String
    Description: Destination cluster bootstrap.
  ECSClusterArn:
    Type: String
    Description: ECS cluster arn
  ECSServiceRoleArn:
    Type: String
    Description: ECS Service role arn
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 1
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 2
  MSKCluster1SG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: MSK Security Group
  MSKCluster2SG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: MSK Security Group
  CreateService:
    Type: String
    Description: If create service
    Default: "true"
  KafkaConnectImage:
    Type: String
    Description: Change this parameters if you build an image and want to use that.
    Default: "arawa3/kafka-connect-mm2"
  DesiredCount:
    Type: String
    Default: 1
  ReplicationFactor:
    Type: String
    Default: 3
  ContainerImage:
    Type: String
    Default: "arawa3/kafka-connect-mm2"
  AuthType:
    Type: String
    Default: IAM
  PluginZipS3Path:
    Type:  String
    Default: ""
Conditions:
  CreateService:  !Equals [!Ref CreateService, 'true']
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}'


  KCTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSGlueSchemaRegistryFullAccess
      Path: /
  KCTaskRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: KCKMSPolicyCFT
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
              - 'kafka-cluster:*'
            Resource: "*"
      Roles:
        - Ref: KCTaskRole
  KCTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties: 
      ContainerDefinitions: 
        - Name: !Sub '${AWS::StackName}'
          Image: !Sub '${ContainerImage}'
          PortMappings:
            - ContainerPort: 8083
            - ContainerPort: 9901
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: kafka-connect
          Environment:
            - Name: BOOTSTRAP_SERVER
              Value: !Ref DestinationKafkaClusterBootstrap
            - Name: GROUP_ID
              Value: !Sub '${AWS::StackName}'
            - Name: CONFIG_STORAGE_TOPIC
              Value: !Sub '${AWS::StackName}-config'
            - Name: OFFSET_STORAGE_TOPIC
              Value: !Sub '${AWS::StackName}-offset'
            - Name: STATUS_STORAGE_TOPIC
              Value: !Sub '${AWS::StackName}-status'
            - Name: REPLICATION_FACTOR
              Value: !Ref ReplicationFactor
            - Name: PLUGIN_ZIP_S3_PATH
              Value: !Ref PluginZipS3Path
            - Name: AWS_REGION
              Value: !Ref "AWS::Region"
            - Name: AUTH_TYPE
              Value: !Ref AuthType
          DockerLabels:
            PROMETHEUS_EXPORTER_PORT: 9901
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      ExecutionRoleArn: !GetAtt KCTaskRole.Arn
      TaskRoleArn: !GetAtt KCTaskRole.Arn
  KCService:
    Type: AWS::ECS::Service
    DependsOn:  KCALBListener
    Condition: CreateService
    Properties:
      Cluster: !Ref ECSClusterArn
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
        - ContainerName: !Sub '${AWS::StackName}'
          ContainerPort: 8083
          TargetGroupArn: !Ref KCALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref KCECSSecurityGroup
            - !Ref MSKCluster1SG
            - !Ref MSKCluster2SG
          AssignPublicIp: ENABLED
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      TaskDefinition: !Ref KCTaskDefinition
      ServiceName: !Sub '${AWS::StackName}'
      LaunchType: FARGATE
  KCALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  KCECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8083
          ToPort: 8083
          SourceSecurityGroupId:
            Fn::GetAtt:
              - KCALBSecurityGroup
              - GroupId
  KCALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      HealthCheckPath: /connectors
      Matcher:
        HttpCode: '200'
      Port: 8083
      Protocol: HTTP
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPC
      TargetType: ip
  KCALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: KCALB
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref KCALBTargetGroup
      LoadBalancerArn: !Ref KCALB
      Port: 80
      Protocol: HTTP
  KCALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AWS::StackName}'
      Scheme: internal
      SecurityGroups:
        - !GetAtt KCALBSecurityGroup.GroupId
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

Outputs:
  KCUrl:
    Description: Kafka Connect URL
    Value: !GetAtt KCALB.DNSName