akhq:
  connections:
    source:
      properties:
        bootstrap.servers: "ip-10-0-0-21.ap-south-1.compute.internal:9092"
    destination:
      properties:
        bootstrap.servers: "ip-10-0-0-21.ap-south-1.compute.internal:9093"

