akhq:
  connections:
    destination:
      properties:
        bootstrap.servers: "b-3:9092,b-1:9092,b-2:9092"
#        bootstrap.servers: "b-3:9098,b-1:9098,b-2:9098"
#        security.protocol: SASL_SSL
#        sasl.mechanism: AWS_MSK_IAM
#        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
#        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
#        ssl.truststore.location: ${JavaHome}/lib/security/cacerts
#        ssl.truststore.password: changeit
    source:
      properties:
        bootstrap.servers: "b-3:9092,b-1:9092,b-2:9092"
#        bootstrap.servers: "b-3:9098,b-1:9098,b-2:9098"
#        security.protocol: SASL_SSL
#        sasl.mechanism: AWS_MSK_IAM
#        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
#        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
#        ssl.truststore.location: ${JavaHome}/lib/security/cacerts
#        ssl.truststore.password: changeit

