server:
  port: 8082
timer:
  interval: 500
  initialDelay: 1000
spring:
  main:
    web-application-type: none
  kafka:
    propertiesFilePath: src/main/resources/kafka.properties
    messageFormat: JSON_WITH_SCHEMA #JSON,JSON_WITH_SCHEMA,AVRO, PROTOBUF
    json:
      mainTopic: test-topic-json
      fallbackTopic : fallback
      schemaName: local-test-topic-json
    json_with_schema:
      mainTopic: test-topic-json-schema
      fallbackTopic: fallback
      schemaFile: src/main/json/TradeJsonSchema.json
      schemaName: local-test-topic-json-schema
    avro:
      mainTopic: test-avro
      fallbackTopic: fallback
      schemaFile: src/main/avro/Trade.avsc
      schemaName: local-testavro
    protobuf:
      mainTopic: test-avro
      fallbackTopic: fallback
      schemaName: local-testprotobuf


