AWSTemplateFormatVersion: '2010-09-09'
Resources:
  mskRedshfitStreamingIngestionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: redshift-streaming-ingestion-permission
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'kafka:GetBootstrapBrokers'
                Resource: "*"
      Path: /service-role/
